### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Mistress-Anna** [biocore/burrito#13]
First, the README is a bit too light, it says the goal is to wrap and control CLI apps, but it doesn't tell which aspects are wrapped and controlled. Also, the only documentation is docstrings on classes. It is good when you use the lib, but not enough for introducing the lib.
There should be at least an example program using this lib, like a "hello, world", demonstrating what burrito can do, and how it should be used.

**Comment by gregcaporaso** [comment]
@Mistress-Anna, have you seen the old PyCogent docs [here](http://pycogent.org/examples/application_controller_framework.html)? We have an [open issue](https://github.com/biocore/burrito/issues/5) to port them, but it's been on the back-burner.

**Comment by Mistress-Anna** [comment]
I saw this after, it's clearer now.
At first, I thought it was a command-line parsing library, not a command-line feeding library (and more).

**Comment by gregcaporaso** [comment]
Ah, makes sense. For command line parsing, you should definitely check out
[click](http://click.pocoo.org/5/) if you haven't seen that yet.
